x-app-base: &app_base
  build: .
  environment:
    DATABASE_URL: postgresql+asyncpg://user:password@db:5432/population_db
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: postgres:15-alpine
    container_name: population_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: population_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d population_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  get_data:
    <<: *app_base
    command: sh -c "export PYTHONPATH=/app && python /app/src/main_get_data.py"

  print_data:
    <<: *app_base
    command: sh -c "export PYTHONPATH=/app && python /app/src/main_print_data.py"

  web:
    <<: *app_base
    command: sh -c "export PYTHONPATH=/app && uvicorn src.app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

volumes:
  postgres_data: